-- OBSOLETO — NÃO EXECUTE.
--
-- Este script desligava o RLS de `partners` "para o app funcionar sem usuários
-- autenticados". Com RLS desligado, a anon key (pública, embarcada no bundle
-- do browser) lia e escrevia CNPJ, CPF e contatos dos responsáveis direto na
-- API REST do Supabase.
--
-- O app nunca precisou disso: as rotas de parceiros usam service_role
-- server-side, atrás de requirePermission('parceiro').
--
-- Se este script já foi executado em algum ambiente, rode
-- `scripts/fix-partners-rls.sql` (ou `sql/021-harden-legacy-rls.sql`) para
-- religar o RLS e restringir o acesso a service_role.
